// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NuneSports.Context;

#nullable disable

namespace NuneSports.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240201155219_SegundaMigracaoAlteracaoPreco")]
    partial class SegundaMigracaoAlteracaoPreco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NuneSports.Model.Produto", b =>
                {
                    b.Property<int>("Codigo_Produto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Codigo_Produto"), 1L, 1);

                    b.Property<string>("Descricao_Produto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome_Produto")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Preco_Produto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo_Produto");

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
